AgendaWebApplication/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AgendaWebApplication.Models
{
    public class Pessoa
    {

        [Display(Name = "Id")]
        public int idPessoa { get; set; }
        [Required(ErrorMessage = "Informe um nome para o contato")]
        public string nomePessoa { get; set; }
        [Required(ErrorMessage = "Informe um telefone para o contato")]
        public string telefonePessoa { get; set; }
        [Required(ErrorMessage = "Informe um e-mail para o contato")]
        public string emailPessoa { get; set; }
    

    }
}

AgendaWebApplication/Controllers/PessoaController.cs
using AgendaWebApplication.Models;
using AgendaWebApplication.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AgendaWebApplication.Controllers
{
    public class PessoaController : Controller
    {
        private PessoaRepository _pessoaR;

        public ActionResult ListPessoa()
        {
            _pessoaR = new PessoaRepository();

            ModelState.Clear();

            return View(_pessoaR.ListPessoa());
        }

        [HttpGet]
        public ActionResult AddPessoa()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddPessoa(Pessoa pessoa)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _pessoaR = new PessoaRepository();

                    if (_pessoaR.AddPessoa(pessoa))
                    {
                        ViewBag.Mensagem = "Pessoa cadastrada com sucesso!";
                    }
                }
                return View();
            }
            catch (Exception)
            {
                return View("ListPessoa");
            }
        }

        public ActionResult UpdatePessoa(int idPessoa)
        {
            _pessoaR = new PessoaRepository();

            return View(_pessoaR.ListPessoa().Find(p => p.idPessoa == idPessoa));
        }

        [HttpPost]
        public ActionResult UpdatePessoa(Pessoa pessoa)
        {
            try
            {
                _pessoaR = new PessoaRepository();
                _pessoaR.UpdatePessoa(pessoa);
                return RedirectToAction("ListPessoa");
            }
            catch (Exception)
            {
                return View("ListPessoa");
            }
        }
        
        public ActionResult DeletePessoa(int idPessoa)
        {
            try
            {
                _pessoaR = new PessoaRepository();
                if (_pessoaR.DeletePessoa(idPessoa))
                {
                    ViewBag.Mensagem = "Pessoa excluida com sucesso!";
                }
                return RedirectToAction("ListPessoa");
            }
            catch (Exception)
            {
                return View("ListPessoa");
            }
        }
    }
}

AgendaWebApplication/Views/Pessoa/AddPessoa.cshtml
@model AgendaWebApplication.Models.Pessoa

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pessoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.nomePessoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nomePessoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nomePessoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefonePessoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefonePessoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefonePessoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailPessoa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailPessoa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailPessoa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green;">
                @ViewBag.Mensagem
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AgendaWebApplication/Views/Pessoa/ListPessoa.cshtml
@model IEnumerable<AgendaWebApplication.Models.Pessoa>

<p>
    @Html.ActionLink("Create New Pessoa", "AddPessoa")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.nomePessoa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefonePessoa)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.emailPessoa)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        @Html.HiddenFor(modelItem => item.idPessoa)
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nomePessoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefonePessoa)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.emailPessoa)
            </td>
            <td>
                @Html.ActionLink("Update", "UpdatePessoa", new { id = item.idPessoa }) |
                @Html.ActionLink("Delete", "DeletePessoa", new { id = item.idPessoa }, new { onclick = "return confirm('Tem certeza que deseja excluir?');" })
            </td>
        </tr>
    }

</table>

AgendaWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Agenda ADO</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "ListPessoa", "Pessoa", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Agenda ADO</p>
        </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>